<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class InsertValueBoMon extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::select(DB::raw("INSERT INTO `mon_hoc` (`ma_mon_hoc`, `ten_mon_tieng_viet`, `ten_mon_tieng_anh`, `so_gio`, `ma_kieu_thi`) VALUES
('BKA_.Net1', 'Ngôn ngữ lập trình C#', 'A Guide to C# Language', '56', '3'),
('BIT_DB2', 'Nguyên lý cơ sở dữ liệu nâng cao', 'Advanced Database Principle', '60', '3'),
('BKA_DB2', 'Nguyên lý cơ sở dữ liệu nâng cao', 'Advanced Database Principle', '60', '3'),
('BKA_AJP', 'Lập trình Java nâng cao', 'Advanced Java Programming', '60', '3'),
('BIT_AP', 'Lập trình nâng cao', 'Advanced Programming', '60', '3'),
('BKA_PHP2', 'Lập trình website PHP - MySQL nâng cao', 'Advanced Web Building with PHP&MySQL', '60', '2'),
('BIT_PHP2', 'Lập trình Website PHP nâng cao', 'Advanced Web Development - PHP Track', '60', '2'),
('BKA_ASA', 'Hệ thống bảo mật ISA', 'ASA', '28', '3'),
('BKA_HAT_BTMT', 'Bảo trì máy tính', 'Bảo trì máy tính', '37.5', '3'),
('BKA_WEB', 'Xây dựng website động bằng HTML5', 'Buiding Dynamic Site using HTML5, CSS3 and Javascript', '72', '3'),
('BIT_NET', 'Xây dựng ứng dụng .Net', 'Building .Net Application', '60', '3'),
('BKA_NET', 'Xây dựng ứng dụng .Net', 'Building .Net Application', '60', '2'),
('BKA_.Net2', 'Lập trình Website ASP.Net', 'Building ASP.Net Web Application', NULL, '3'),
('BIT_WEB', 'Xây dựng website động', 'Building Dynamic Site', '60', '3'),
('BIT_ACC', 'Kế toán doanh nghiệp', 'Business Accounting', '45', '1'),
('BIT_LAW', 'Luật kinh tế', 'Business Law', '45', '1'),
('BKA_HAT_CTMT', 'Cấu trúc máy tính', 'Cấu trúc máy tính', '41.25', '3'),
('BKA_NA1', 'Nguyên tắc cơ bản của mạng máy tính (CCNA1)', 'CCNA 1', '40', '3'),
('BKA_NA2', 'Các giao thức  và khía niệm định tuyến (CCNA2)', 'CCNA 2', '70', '3'),
('BKA_NA3', 'Chuyển mạch Lan và mạng không dây (CCNA3)', 'CCNA 3', '60', '3'),
('BKA_NA4', 'Truy cập mạng WAN (CCNA4)', 'CCNA 4', '50', '3'),
('BKA_CyberOp', 'Quản trị vận hành bảo mật mạng', 'CCNA Cyber Operation', '60', '3'),
('BKA_SE', 'An ninh mạng Cisco (CCNA- SEC)', 'CCNA- SEC', '70', '3'),
('BKA_CCNASE', 'An toàn mạng Cisco (CCNA-SEC)', 'CCNA-SEC', '70', '3'),
('BKA_HAT_CSDL', 'Cơ sở dữ liệu', 'Cơ sở dữ liệu', '56.25', '3'),
('BKA_HAT_MKD', 'Công nghệ mạng không dây', 'Công nghệ mạng không dây', '37.5', '3'),
('BIT_CMS', 'Hệ quản trị nội dung', 'Content Management System', '30', '2'),
('BKA_CMS', 'Hệ quản trị nội dung', 'Content Management System', '30', '2'),
('BIT_DSA', 'Cấu trúc dữ liệu và giải thuật', 'Data Structure and Algorithm', '60', '3'),
('BKA_DSA', 'Cấu trúc dữ liệu và giải thuật', 'Data Structure and Algorithm', '60', '2'),
('BIT_DB1', 'Nguyên lý cơ sở dữ liệu', 'Database Principle', '60', '3'),
('BKA_DB1', 'Nguyên lý cơ sở dữ liệu', 'Database Principle', '60', '3'),
('BIT_ECOM2', 'Quản trị thương mại điện tử', 'Digital Businesss and E-Commerce Management', '45', '3'),
('BIT_DMAR1', 'Digital Marketing - SEO/SEM', 'Digital Marketing - SEO/SEM', '45', '3'),
('BIT_DMAR2', 'Digital Marketing - chiến lược, thực hiện', 'Digital Marketing - Strategies, Implementations and Practices', '45', '3'),
('BIT_ECOM1', 'Thương mại điện tử cơ bản', 'E-Commerce - Principles and Technologies', '45', '1'),
('BIT_FINANCE', 'Kinh tế học', 'Ecomonics', '45', '1'),
('BKA_HAT_AV2', 'Anh Văn 2', 'English 2', '30', '1'),
('BIT_EB', 'Tiếng anh chuyên ngành quản trị kinh doanh BIT', 'English for Business', '55', '1'),
('BIT_ESE', 'Tiếng anh chuyên ngành lập trình BIT', 'English for Software Engineer', '60', '1'),
('BKA_ESE', 'Tiếng anh chuyên ngành lập trình', 'English for Software Engineer', '60', '1'),
('BKA_HAT_AV1', 'Anh Văn 1', 'English1', '24', '1'),
('BKA_Exchange2016', 'Quản trị Exchange Server', 'Exchange 2016', '40', '3'),
('BIT_XML', 'Ngôn ngữ XML', 'Extensible Markup language', '30', '1'),
('BKA_XML', 'Ngôn ngữXML', 'Extensible Markup Language', '30', '1'),
('BIT_GE', 'Tiếng anh tổng quát', 'General English', '30', '1'),
('BIT_GRADUATION', 'Luận văn tốt nghiệp', 'Graduation Dissertation', '100', '3'),
('BKA_GRADUATION', 'Đồ án tốt nghiệp', 'Graduation Project', '120', '3'),
('BIT_HRM', 'Quản trị nguồn nhân lực', 'Human Resources Management', '45', '3'),
('BKA_ITE', 'Chuyên viên CNTT Quốc Tế', 'Information Technology Essentials', NULL, '3'),
('BKA_IOT', 'Internet Vạn Vật', 'Internet of Things', '30', '3'),
('BIT_INTERNSHIP', 'Thực tập', 'Internship', '100', '2'),
('BKA_INTERN', 'Thực tập', 'Internship', '120', '3'),
('BIT_ITF', 'Tin học cơ bản', 'IT Fundamental', '45', '2'),
('BKA_ITF', 'Tin học cơ bản', 'IT Fundamental', '30', '2'),
('BKA_HAT_KTDT', 'Kỹ thuật điện tử', 'Kỹ thuật điện tử', '41.25', '3'),
('BKA_LPI101', 'Chuyên viên quản trị hệ thống Linux - phần 1', 'LPI 101', '30', '3'),
('BKA_LPI102', 'Chuyên viên quản trị hệ thống Linux - phần 2', 'LPI 102', '30', '3'),
('BIT_MATH', 'Toán kinh tế', 'Mathematics for Business Analytics', '60', '1'),
('BKA_MCSA1', 'Cài đặt và cấu hình trên hệ thống máy chủ Window Server', 'MCSA2016 (70-740)', '50', '3'),
('BKA_MCSA2', 'Quản  trị hệ thống máy chủ Window Server', 'MCSA2016 (70-741)', '50', '3'),
('BKA_MCSA3', 'Cấu hình các dịch vụ nâng cao trên Window Server', 'MCSA2016 (70-742)', '50', '3'),
('BKA_MOBILE', 'Lập trình thiết bị di động', 'Mobile Development', '60', '2'),
('BKA_AND', 'Lập trình Mobile Android', 'Mobile Development with Android', '60', '2'),
('BKA_PRJNetwork', 'Dự án cho kỹ sư mạng và hệ thống', 'Network and System Engineer Project', '90', '2'),
('BKA_HAT_MMT', 'Nhập môn mạng máy tính', 'Nhập môn mạng máy tính', '37.5', '3'),
('BKA_HAT_PL', 'Pháp luật', NULL, '23', '1'),
('HAT_MH05', 'Anh văn 1', NULL, '35', '1'),
('HAT_MH12', 'Cài đặt và bảo trì máy tính', NULL, '35', '3'),
('BKA_VMWare', 'Triển khai và quản trị hệ thống ảo hóa Vmware', NULL, '40', '3'),
('BKA_HAT_XLA', 'Xử lý ảnh', NULL, '41.25', '3'),
('BKA_HAT_THCB', 'Tin học căn bản', NULL, '42.5', '3'),
('BKA_HAT_TOANCC', 'Toán cao cấp', NULL, '45', '1'),
('BKA_CEH', 'Hacker mũ trắng (CEHv9)', NULL, '50', '3'),
('BKA_HAT_LTCB', 'Lập trình căn bản', NULL, '56.25', '3'),
('BKA_HAT_CT', 'Chính trị', NULL, '60', '1'),
('HAT_MH15', 'Cấu trúc dữ liệu và giải thuật', NULL, '85', '3'),
('HAT_MH18', 'Anh văn chuyên ngành', NULL, NULL, '1'),
('HAT_MH22', 'Thực tập nhận thức', NULL, NULL, '2'),
('HAT_MH30', 'Thực tập nghề nghiệp', NULL, NULL, '2'),
('HAT_MH21', 'Hệ quản trị CSDL', NULL, NULL, '3'),
('HAT_MH27', 'Thiết kế web bằng phần mềm mã nguồn mở', NULL, NULL, '3'),
('HAT_MH29', 'Anh văn 1', NULL, NULL, '3'),
('HAT_MH38', 'Nhập môn mạng máy tính', NULL, NULL, '3'),
('HAT_MH41', 'Công nghệ mạng không dây', NULL, NULL, '3'),
('HAT_MH48', 'Hệ thống bảo mật TMG', NULL, NULL, '3'),
('BKA_NP', 'Lập trình mạng', NULL, NULL, '3'),
('HAT_MH16', 'Lập trình hướng đối tượng', NULL, NULL, '3'),
('HAT_MH20', 'Cơ sở dữ liệu', NULL, NULL, '3'),
('HAT_MH23', 'Hệ quản trị CSDL SQL Server', NULL, NULL, '3'),
('HAT_MH24', 'Lập trình Window2 (ADO.NET)', NULL, NULL, '3'),
('HAT_MH25', 'Lập trình Web 1(ASP.NET)', NULL, NULL, '3'),
('HAT_MH31', 'Lập trình Window 3 (Service)', NULL, NULL, '3'),
('HAT_MH32', 'Lập trình Web 2 (XML…)', NULL, NULL, '3'),
('HAT_MH33', 'Nhập môn công nghệ phần mềm', NULL, NULL, '3'),
('HAT_MH34', 'Xây dựng phần mềm quản lý', NULL, NULL, '3'),
('HAT_MH45', 'Lập trình Java', NULL, NULL, '3'),
('HAT_MH49', 'Thiết kế Web bằng phần mềm mã nguồn mở', NULL, NULL, '3'),
('HAT_MH52', 'Lập trình mạng', NULL, NULL, '3'),
('HAT_MH28', 'Hệ điều hành mã nguồn mở', NULL, NULL, '3'),
('HAT_MH35', 'Lập trình Linux', NULL, NULL, '3'),
('HAT_MH42', 'Thiết lập, XD & QT hệ thống WebServer &MailServer', NULL, NULL, '3'),
('HAT_MH43', 'Hệ điều hành Linux', NULL, NULL, '3'),
('HAT_MH47', 'Bảo trì hệ thống máy chủ', NULL, NULL, '3'),
('HAT_MH50', 'Quản trị CSDL khách chủ', NULL, NULL, '3'),
('BKA_CCNP', 'CCNP', NULL, NULL, '3'),
('HAT_MH39', 'Quản trị mạng 1 (CĐ&QTM)', NULL, NULL, '3'),
('HAT_MH44', 'Quản trị mạng 2', NULL, NULL, '3'),
('HAT_MH46', 'Thiết kế xây dựng mạng LAN', NULL, NULL, '3'),
('HAT_MH51', 'An toàn mạng', NULL, NULL, '3'),
('BKA_SA', 'Phân tích thiết kế hệ thống', NULL, NULL, '3'),
('HAT_MH06', 'Giáo dục Quốc phòng', NULL, NULL, '3'),
('HAT_MH07', 'Giáo dục  thể chất', NULL, NULL, '3'),
('HAT_MH17', 'Lập trình Window 1 (VB, C#)', NULL, NULL, '3'),
('HAT_MH19', 'Nguyên lý hệ điều hành', NULL, NULL, '3'),
('HAT_MH26', 'Phân tích thiết kế hệ thống', NULL, NULL, '3'),
('HAT_MH36', 'Thực tập tốt nghiệp', NULL, NULL, '3'),
('HAT_MH37', 'Đồ án tốt nghiệp', NULL, NULL, '3'),
('HAT_MH40', 'Kỹ thuật truyền số liệu', NULL, NULL, '3'),
('BIT_OOP', 'Lập trình hướng đối tượng', 'Object Oriented Programming', '60', '3'),
('BKA_OOP', 'Lập trình hướng đối tượng', 'Object Oriented Programming', '60', '3'),
('BKA_CCNA4OnThi', 'Ôn Thi CCNA4', 'Ôn Thi CCNA4', NULL, '1'),
('BKA_MCSAOnThi', 'Ôn Thi MCSA', 'Ôn Thi MCSA', NULL, '1'),
('BKA_PROG', 'Kiến thức lập trình dành cho kỹ sư mạng và hệ thống', 'Programming for Network and System engineer', '70', '2'),
('BIT_PLD', 'Nguyên lý lập trình', 'Programming Logic and Design', '60', '2'),
('BKA_C', 'Nguyên lý lập trình C', 'Programming Theory and C Programming', '60', '3'),
('BIT_PRJ1', 'Đồ án 1', 'Project 1', '75', '2'),
('BKA_PRJ1', 'Đồ án 1', 'Project 1', '75', '2'),
('BIT_PRJ2', 'Đồ án 2', 'Project 2', '75', '2'),
('BKA_PRJ2', 'Đồ án 2', 'Project 2', '75', '2'),
('BIT_PRJ3', 'Đồ án 3', 'Project 3', '45', '3'),
('BKA_PRJ3', 'Đồ án 3', 'Project 3', '60', '2'),
('BKA_SQL2016', 'Quản trị CSDL với SQL Server', 'Quản trị CSDL với SQL Server 2016 (70-764)', '30', '3'),
('BIT_MAR', 'Marketing căn bản', 'Sales and Marketing', '45', '1'),
('BKA_ICT', 'Tiếng anh chuyên ngành quản trị mạng', 'Tiếng anh chuyên ngành quản trị mạng', '60', '1'),
('BKA_HAT_THVP', 'Tin học văn phòng', 'Tin học văn phòng', '37.5', '3'),
('BIT_PHP1', 'Lập trình Website PHP', 'Web Programming - PHP Track', '60', '2'),
('BIT_JSP', 'Xây dựng ứng dụng Web bằng Java', 'Web Programming with JSP Servlet', '60', '2'),
('BKA_JSP', 'Xây dựng ứng dụng Web bằng Java', 'Web Programming with JSP Servlet', '60', '2'),
('BKA_PHP1', 'Lập trình website PHP - MySQL', 'Web Programming with PHP&MySQL', '72', '2'),
('BKA_WCC', 'Webservices và điện toán đám mây', 'Webservices and Cloud Computing Simple', NULL, '3')"));
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
